name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy README into docs
        run: cp README.md docs/index.md
